---
- name: Install and configure Apache
  hosts: localhost
  become: yes
  tasks:
    - name: Update the package index
      shell: |
        #!/bin/bash
        sudo apt-get update -y

    - name: Install Apache
      shell: |
        #!/bin/bash
        sudo apt-get install apache2 -y

    - name: Ensure Apache is enabled and running
      shell: |
        #!/bin/bash
        sudo systemctl enable apache2
        sudo systemctl start apache2

    - name: Create a test HTML page
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Dickson Kimani Assignment</title>
          </head>
          <body>
              <h1>Dickson Kimani Assignment Page</h1>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure proper permissions for the web directory
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

